### ISSUE TITLE
Error when navigating from last page to second to last page (Update: Can't Paginate Backward)

### ISSUE THREAD

**Issue by anjolaoluwaakindipe** [health-management-system/hms-application#29]
I commented a Todo for the PatientInfo/Profile.tsx  at line 85. This todo was created due to errors in the backend while navigating from the last page to the second to the last page in the health record table. To handle the error for now, I made sure to decrement the last page by 1 if the number of pages is greater than one. The todo also has direction on how to correct the pagination on the front end once the backend pagination is fixed.

**Update:** Turns out user cannot paginate backwards after the second page. This is an known bug existing in the backend repo

Change implemented by PR #28

```

81        // TODO: this snippet of code takes the second to the last page as the lastpage,
82       // this is due to errors coming from the backend when navigating from the last page to the page before the last page
83        // SOLUTION AFTER BACKEND FIX: replace the code in the setLastPage() function with a simple
84       // Math.ceil(total_items/items_per_page)
85        result.result != null &&
            setLastPage(
                Math.ceil(
                    result.result.records.total_items /
                        result.result.records.items_per_page
                ) - 1 || Math.ceil(result.result.records.total_items /
                        result.result.records.items_per_page)
            );
86        // TODO_END

```

**Comment by dakotawong** [comment]
Fixed by PR #40
